todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('admin/', admin.site.urls),
    path('todos/', include('todolist.urls')),
]

todo_manager/todolist/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'todolist'
urlpatterns = [
    # path('', views.TodoListIndexView.as_view(), name='index'),
    path('', views.TodoListIndexView.as_view(), name='index'),
    path('list/', views.TodoListView.as_view(), name='list'),
    path('done/', views.TodoListDoneView.as_view(), name='done'),
    path('<int:pk>/', views.TodoDetailView.as_view(), name='detail'),
]

todo_manager/todolist/models.py
from django.db import models

class TodoItem(models.Model):
    class Meta:
        ordering = ('id',)
        verbose_name = "ToDo Item"

    title = models.CharField(max_length=255)
    done = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.title}"

todo_manager/todolist/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from .models import TodoItem

def index_view(request: HttpRequest) -> HttpResponse:
    todo_items = TodoItem.objects.all()
    return render(request, 'todolist/index.html', context={
        'todo_items': todo_items,
    })

class TodoListIndexView(ListView):
    template_name = 'todolist/index.html'
    model = TodoItem
    queryset = TodoItem.objects.all()

class TodoListView(ListView):
    model = TodoItem

class TodoListDoneView(ListView):
    queryset = TodoItem.objects.filter(done=True).all()

class TodoDetailView(DetailView):
    model = TodoItem

todo_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Base Title{% endblock title %}</title>
</head>
<body>
  {% include 'components/navbar.html' %}

  {% block body %}
    Base Body
  {% endblock body %}
  <footer>
    &copy; Django TODO App
      {% block footer %}
      {% endblock footer %}
  </footer>
</body>
</html>

todo_manager/templates/components/navbar.html
<nav>
    <ul>
      <li><a href="{% url 'index' %}">Home</a></li>
      <li><a href="{% url 'todolist:index' %}">ToDo List</a></li>
      <li><a href="#">About</a></li>
    </ul>
</nav>
<h3>{% now "jS F Y" %}</h3>

todo_manager/templates/index.html
{% extends "base.html" %}

{% block title %}
  Todo App Index
{% endblock title %}

{% block body %}
  <h1>Welcome to our TODO app!</h1>
  <h2>Work in Progress</h2>
{% endblock body %}

todo_manager/todolist/templates/todolist/base.html
{% extends 'base.html' %}

{% block footer %}
    ToDo List
{% endblock footer %}

todo_manager/todolist/templates/todolist/components/todo_items_list.html
<ul>
    {% for todo in object_list %}
        <li>
            <a href="{% url 'todolist:detail' pk=todo.id %}">
                {{ todo.title }}
                {% if todo.done %}
                    ✅
                {% else %}
                    ❌
                {% endif %}
            </a>
        </li>
    {% endfor %}
</ul>

todo_manager/todolist/templates/todolist/index.html
{% extends 'todolist/base.html' %}

{% block title %}
    ToDo List App
{% endblock title %}

{% block body %}
    <h1>ToDo List App</h1>
    <ul>
        <li><a href="{% url 'todolist:list' %}">All ToDo items</a></li>
        <li><a href="{% url 'todolist:done' %}">Done ToDo items</a></li>
    </ul>
    <h2>ToDos:</h2>
    {% include 'todolist/components/todo_items_list.html' %}
{% endblock %}

todo_manager/todolist/templates/todolist/todoitem_detail.html
{% extends 'todolist/base.html' %}

{% block title %}
    Todo #{{ object.id }}
{% endblock title %}

{% block body %}
    <h3>Todo:</h3>
    <div>
        <div>Title: <strong>{{ object.title }}</strong></div>
        <div>Done: <strong>{{ object.done }}</strong></div>
    </div>
{% endblock %}

todo_manager/todolist/templates/todolist/todoitem_list.html
{% extends 'todolist/base.html' %}

{% block title %}
    ToDo List
{% endblock title %}

{% block body %}
    <h1>ToDo List</h1>
    <h2>ToDos:</h2>
    {% include 'todolist/components/todo_items_list.html' %}
{% endblock %}